# Add your Python code here. E.g.
from microbit import *


while True:
    display.scroll('Hello, World!')
    display.scroll("I am Ruben")
    display.show(Image.HEART)
    sleep(500)
    display.show(Image.HEART_SMALL)
    sleep(500)
    display.scroll('i have some questions for you')
    display.show('1')
    display.scroll('welke dag kwam ik de laat')
    display.show('A')
    display.scroll('mandag')
    display.show('B')
    display.scroll('woensdag')
    display.show('C')
    display.scroll('dinsdag')
    display.show('2')
    display.scroll('waar woon ik')
    display.show('A')
    display.scroll('schagen')
    display.show('B')
    display.scroll('amsterdam')
    display.show('C')
    display.scroll('alkmaar')
    display.show('3')
    display.scroll('hoeveel huisdieren heb ik')
    display.show('A')
    display.show('8')
    display.show('B')
    display.show('5')
    display.show('C')
    display.show('3')
    sleep(1000)
    